# Generated by Django 5.1.1 on 2025-08-09 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_boardmember_board'),
        ('tasks', '0002_alter_task_options_alter_task_assignee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='boards.board', verbose_name='Доска'),
        ),
    ]
