# Generated by Django 5.1.1 on 2025-08-08 18:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardmember',
            options={'ordering': ('-added_at',), 'verbose_name': 'Участник доски', 'verbose_name_plural': 'Участники доски'},
        ),
        migrations.AlterUniqueTogether(
            name='boardmember',
            unique_together={('board', 'user')},
        ),
    ]
