# Generated by Django 5.1.1 on 2025-08-09 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_boardmember_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='boards.board', verbose_name='Доска'),
        ),
    ]
