# Generated by Django 5.1.1 on 2025-08-09 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_boardmember_board'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принято'), ('declined', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата приглашения')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='boards.board', verbose_name='Доска')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Пригласил')),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Приглашенный пользователь')),
            ],
            options={
                'verbose_name': 'Приглашение в доску',
                'verbose_name_plural': 'Приглашения в доски',
                'ordering': ('-invited_at',),
                'unique_together': {('board', 'invited_user')},
            },
        ),
    ]
